name = "translation-chat-app"
compatibility_date = "2024-08-30"
pages_build_output_dir = ".svelte-kit/cloudflare"

[env.production.vars]
# Environment variables will be set in Cloudflare dashboard

[env.preview.vars]
# Environment variables for preview deployments